#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Apr 11 10:22:11 2018

@author: mc
"""
import csv
numberOfStations = 49
csvfilePath = "/Users/mc/Desktop/bestSolMilano.csv"
with open(csvfilePath, 'rt') as csvfile:
    csvreader = csv.reader(csvfile, delimiter=',')
    next(csvreader) # jump header
    for row in csvreader:
        if row[0] == str(numberOfStations):
            Stations = row[1].replace("[", "").replace("]", "").split(",")
    Stations = [int(i) for i in Stations]
        
        